
DROP TABLE EFFETTUA          CASCADE CONSTRAINTS;
DROP TABLE RICEVE            CASCADE CONSTRAINTS;
DROP TABLE CONSULENZA        CASCADE CONSTRAINTS;
DROP TABLE VISITA            CASCADE CONSTRAINTS;
DROP TABLE TURNO_EFFETTUATO  CASCADE CONSTRAINTS;
DROP TABLE TURNO_PROGRAMMATO CASCADE CONSTRAINTS;
DROP TABLE PRENOTAZIONE      CASCADE CONSTRAINTS;
DROP TABLE DOCUMENTO         CASCADE CONSTRAINTS;
DROP TABLE ENTE              CASCADE CONSTRAINTS;
DROP TABLE PULISCE           CASCADE CONSTRAINTS;
DROP TABLE FORNISCE          CASCADE CONSTRAINTS;
DROP TABLE DIETA             CASCADE CONSTRAINTS;
DROP TABLE DITTA_RISTORANTE  CASCADE CONSTRAINTS;
DROP TABLE DITTA_PULIZIE     CASCADE CONSTRAINTS;
DROP TABLE AZIENDA_ESTERNA   CASCADE CONSTRAINTS;
DROP TABLE NECESSITA         CASCADE CONSTRAINTS;
DROP TABLE PAI               CASCADE CONSTRAINTS;
DROP TABLE ASSUME            CASCADE CONSTRAINTS;
DROP TABLE SOFFRE            CASCADE CONSTRAINTS;
DROP TABLE TRATTAMENTO       CASCADE CONSTRAINTS;
DROP TABLE FARMACO           CASCADE CONSTRAINTS;
DROP TABLE MALATTIA          CASCADE CONSTRAINTS;
DROP TABLE RESIDENTE         CASCADE CONSTRAINTS;
DROP TABLE CAMERA            CASCADE CONSTRAINTS;
DROP TABLE REPARTO           CASCADE CONSTRAINTS;
DROP TABLE MEDICO            CASCADE CONSTRAINTS;
DROP TABLE CONTRATTO         CASCADE CONSTRAINTS;
DROP TABLE OPERATORE         CASCADE CONSTRAINTS;
DROP TABLE TUTORE            CASCADE CONSTRAINTS;
DROP TABLE PARENTE           CASCADE CONSTRAINTS;
DROP TABLE PERSONALE         CASCADE CONSTRAINTS;
DROP TABLE PERSONA           CASCADE CONSTRAINTS;


CREATE TABLE PERSONA (
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    NOME           VARCHAR2(64) NOT NULL,
    COGNOME        VARCHAR2(64) NOT NULL,
    DATA_NASCITA   DATE         NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY (CODICE_FISCALE)
);

CREATE TABLE PERSONALE (
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_PERSONALE PRIMARY KEY (CODICE_FISCALE),
    CONSTRAINT FK_PERSONALE_PERSONA
        FOREIGN KEY (CODICE_FISCALE) REFERENCES PERSONA(CODICE_FISCALE)
);

CREATE TABLE PARENTE (
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_PARENTE PRIMARY KEY (CODICE_FISCALE),
    CONSTRAINT FK_PARENTE_PERSONA
        FOREIGN KEY (CODICE_FISCALE) REFERENCES PERSONA(CODICE_FISCALE)
);

CREATE TABLE TUTORE (
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_TUTORE PRIMARY KEY (CODICE_FISCALE),
    CONSTRAINT FK_TUTORE_PERSONA
        FOREIGN KEY (CODICE_FISCALE) REFERENCES PERSONA(CODICE_FISCALE)
);

CREATE TABLE CONTRATTO (
    CODICE_CONTRATTO         NUMBER        NOT NULL,
    TIPO_CONTRATTO           VARCHAR2(64)  NOT NULL,
    PAGA_ORARIA              NUMBER        NOT NULL,
    TASSA_DETRATTA           NUMBER        NOT NULL,
    CODICE_FISCALE_PERSONALE VARCHAR2(16)  NOT NULL,
    CONSTRAINT PK_CONTRATTO PRIMARY KEY (CODICE_CONTRATTO),
    CONSTRAINT FK_CONTRATTO_PERSONALE
        FOREIGN KEY (CODICE_FISCALE_PERSONALE) REFERENCES PERSONALE(CODICE_FISCALE)
);

CREATE TABLE OPERATORE (
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_OPERATORE PRIMARY KEY (CODICE_FISCALE),
    CONSTRAINT FK_OPERATORE_PERSONALE
        FOREIGN KEY (CODICE_FISCALE) REFERENCES PERSONALE(CODICE_FISCALE)
);

CREATE TABLE MEDICO (
    CODICE_FISCALE   VARCHAR2(16) NOT NULL,
    CODICE_CONTRATTO NUMBER       NOT NULL,
    CONSTRAINT PK_MEDICO PRIMARY KEY (CODICE_FISCALE),
    CONSTRAINT FK_MEDICO_PERSONALE
        FOREIGN KEY (CODICE_FISCALE) REFERENCES PERSONALE(CODICE_FISCALE),
    CONSTRAINT FK_MEDICO_CONTRATTO
        FOREIGN KEY (CODICE_CONTRATTO) REFERENCES CONTRATTO(CODICE_CONTRATTO)
);


CREATE TABLE REPARTO (
    CODICE_REPARTO      VARCHAR2(16) NOT NULL,
    NOME_REPARTO        VARCHAR2(64) NOT NULL,
    CODICE_RESPONSABILE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_REPARTO PRIMARY KEY (CODICE_REPARTO),
    CONSTRAINT FK_REPARTO_MEDICO
        FOREIGN KEY (CODICE_RESPONSABILE) REFERENCES MEDICO(CODICE_FISCALE)
);

CREATE TABLE CAMERA (
    NUMERO_CAMERA  NUMBER        NOT NULL,
    PIANO          NUMBER        NOT NULL,
    LETTI_TOTALI   NUMBER        NOT NULL,
    CODICE_REPARTO VARCHAR2(16)  NOT NULL,
    CONSTRAINT PK_CAMERA PRIMARY KEY (NUMERO_CAMERA),
    CONSTRAINT FK_CAMERA_REPARTO
        FOREIGN KEY (CODICE_REPARTO) REFERENCES REPARTO(CODICE_REPARTO)
);

CREATE TABLE RESIDENTE (
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    NUMERO_CAMERA  NUMBER       NOT NULL,
    CONSTRAINT PK_RESIDENTE PRIMARY KEY (CODICE_FISCALE),
    CONSTRAINT FK_RESIDENTE_PERSONA
        FOREIGN KEY (CODICE_FISCALE) REFERENCES PERSONA(CODICE_FISCALE),
    CONSTRAINT FK_RESIDENTE_CAMERA
        FOREIGN KEY (NUMERO_CAMERA) REFERENCES CAMERA(NUMERO_CAMERA)
);


CREATE TABLE MALATTIA (
    CODICE      VARCHAR2(16) NOT NULL,
    NOME        VARCHAR2(64) NOT NULL,
    DESCRIZIONE CLOB,
    LIVELLO     VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_MALATTIA PRIMARY KEY (CODICE)
);

CREATE TABLE FARMACO (
    CODICE_FARMACO VARCHAR2(16) NOT NULL,
    NOME           VARCHAR2(64) NOT NULL,
    DOSE           NUMBER       NOT NULL,
    FASCIA_ORARIA  VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_FARMACO PRIMARY KEY (CODICE_FARMACO)
);

CREATE TABLE TRATTAMENTO (
    CODICE_TRATTAMENTO VARCHAR2(16) NOT NULL,
    OBIETTIVO          CLOB,
    ESITO              CLOB,
    RAGGIUNTO          CHAR(1) DEFAULT 'N'
        CONSTRAINT CK_TRATTAMENTO_RAGGIUNTO CHECK (RAGGIUNTO IN ('S', 'N')),
    CONSTRAINT PK_TRATTAMENTO PRIMARY KEY (CODICE_TRATTAMENTO)
);

CREATE TABLE SOFFRE (
    CODICE         VARCHAR2(16) NOT NULL,
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_SOFFRE PRIMARY KEY (CODICE, CODICE_FISCALE),
    CONSTRAINT FK_SOFFRE_MALATTIA
        FOREIGN KEY (CODICE) REFERENCES MALATTIA(CODICE),
    CONSTRAINT FK_SOFFRE_RESIDENTE
        FOREIGN KEY (CODICE_FISCALE) REFERENCES RESIDENTE(CODICE_FISCALE)
);

CREATE TABLE ASSUME (
    CODICE_FARMACO VARCHAR2(16) NOT NULL,
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_ASSUME PRIMARY KEY (CODICE_FARMACO, CODICE_FISCALE),
    CONSTRAINT FK_ASSUME_FARMACO
        FOREIGN KEY (CODICE_FARMACO) REFERENCES FARMACO(CODICE_FARMACO),
    CONSTRAINT FK_ASSUME_RESIDENTE
        FOREIGN KEY (CODICE_FISCALE) REFERENCES RESIDENTE(CODICE_FISCALE)
);

CREATE TABLE PAI (
    CODICE_PAI               VARCHAR2(16) NOT NULL,
    CODICE_FISCALE_RESIDENTE VARCHAR2(16) NOT NULL,
    DATA_REDAZIONE           DATE         NOT NULL,
    DATA_REVISIONE           DATE,
    DIAGNOSI                 CLOB         NOT NULL,
    DATA_DIMISSIONE          DATE,
    CONSTRAINT PK_PAI PRIMARY KEY (CODICE_PAI),
    CONSTRAINT FK_PAI_RESIDENTE
        FOREIGN KEY (CODICE_FISCALE_RESIDENTE) REFERENCES RESIDENTE(CODICE_FISCALE)
);

CREATE TABLE NECESSITA (
    CODICE_TRATTAMENTO VARCHAR2(16) NOT NULL,
    CODICE_PAI         VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_NECESSITA PRIMARY KEY (CODICE_TRATTAMENTO, CODICE_PAI),
    CONSTRAINT FK_NECESSITA_TRATTAMENTO
        FOREIGN KEY (CODICE_TRATTAMENTO) REFERENCES TRATTAMENTO(CODICE_TRATTAMENTO),
    CONSTRAINT FK_NECESSITA_PAI
        FOREIGN KEY (CODICE_PAI) REFERENCES PAI(CODICE_PAI)
);

CREATE TABLE CONSULENZA (
    DATA_CONSULENZA DATE NOT NULL,
    NOTE_CONSULENZA CLOB,
    CONSTRAINT PK_CONSULENZA PRIMARY KEY (DATA_CONSULENZA)
);

CREATE TABLE EFFETTUA (
    DATA_CONSULENZA       DATE         NOT NULL,
    CODICE_FISCALE_MEDICO VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_EFFETTUA PRIMARY KEY (DATA_CONSULENZA, CODICE_FISCALE_MEDICO),
    CONSTRAINT FK_EFFETTUA_CONSULENZA
        FOREIGN KEY (DATA_CONSULENZA) REFERENCES CONSULENZA(DATA_CONSULENZA),
    CONSTRAINT FK_EFFETTUA_MEDICO
        FOREIGN KEY (CODICE_FISCALE_MEDICO) REFERENCES MEDICO(CODICE_FISCALE)
);

CREATE TABLE RICEVE (
    CODICE_PAI      VARCHAR2(16) NOT NULL,
    DATA_CONSULENZA DATE         NOT NULL,
    CONSTRAINT PK_RICEVE PRIMARY KEY (CODICE_PAI, DATA_CONSULENZA),
    CONSTRAINT FK_RICEVE_PAI
        FOREIGN KEY (CODICE_PAI) REFERENCES PAI(CODICE_PAI),
    CONSTRAINT FK_RICEVE_CONSULENZA
        FOREIGN KEY (DATA_CONSULENZA) REFERENCES CONSULENZA(DATA_CONSULENZA)
);


CREATE TABLE AZIENDA_ESTERNA (
    PARTITA_IVA              VARCHAR2(16) NOT NULL,
    NOME_AZIENDA             CLOB,
    EMAIL                    CLOB,
    NUMERO_DI_TELEFONO       VARCHAR2(16) NOT NULL,
    PEC                      CLOB,
    CODICE_FISCALE_OPERATORE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_AZIENDA_ESTERNA PRIMARY KEY (PARTITA_IVA),
    CONSTRAINT FK_AZIENDA_ESTERNA_OPERATORE
        FOREIGN KEY (CODICE_FISCALE_OPERATORE) REFERENCES OPERATORE(CODICE_FISCALE)
);

CREATE TABLE DITTA_PULIZIE (
    PARTITA_IVA VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_DITTA_PULIZIE PRIMARY KEY (PARTITA_IVA),
    CONSTRAINT FK_DITTA_PULIZIE_AZIENDA
        FOREIGN KEY (PARTITA_IVA) REFERENCES AZIENDA_ESTERNA(PARTITA_IVA)
);

CREATE TABLE DITTA_RISTORANTE (
    PARTITA_IVA VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_DITTA_RISTORANTE PRIMARY KEY (PARTITA_IVA),
    CONSTRAINT FK_DITTA_RISTORANTE_AZIENDA
        FOREIGN KEY (PARTITA_IVA) REFERENCES AZIENDA_ESTERNA(PARTITA_IVA)
);

CREATE TABLE DIETA (
    NOME      VARCHAR2(64)  NOT NULL,
    TIPOLOGIA VARCHAR2(64),
    NOTE      VARCHAR2(256),
    CONSTRAINT PK_DIETA PRIMARY KEY (NOME)
);

CREATE TABLE FORNISCE (
    PARTITA_IVA VARCHAR2(16) NOT NULL,
    NOME        VARCHAR2(64) NOT NULL,
    CONSTRAINT PK_FORNISCE PRIMARY KEY (PARTITA_IVA, NOME),
    CONSTRAINT FK_FORNISCE_DITTA_RIST
        FOREIGN KEY (PARTITA_IVA) REFERENCES DITTA_RISTORANTE(PARTITA_IVA),
    CONSTRAINT FK_FORNISCE_DIETA
        FOREIGN KEY (NOME) REFERENCES DIETA(NOME)
);

CREATE TABLE PULISCE (
    NUMERO_CAMERA NUMBER       NOT NULL,
    PARTITA_IVA   VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_PULISCE PRIMARY KEY (NUMERO_CAMERA, PARTITA_IVA),
    CONSTRAINT FK_PULISCE_CAMERA
        FOREIGN KEY (NUMERO_CAMERA) REFERENCES CAMERA(NUMERO_CAMERA),
    CONSTRAINT FK_PULISCE_DITTA_PULIZIE
        FOREIGN KEY (PARTITA_IVA) REFERENCES DITTA_PULIZIE(PARTITA_IVA)
);

CREATE TABLE ENTE (
    PARTITA_IVA      VARCHAR2(16)  NOT NULL,
    NOME_ISTITUZIONE VARCHAR2(128) NOT NULL,
    CONSTRAINT PK_ENTE PRIMARY KEY (PARTITA_IVA)
);

CREATE TABLE DOCUMENTO (
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    SCADENZA       DATE         NOT NULL,
    PARTITA_IVA    VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_DOCUMENTO PRIMARY KEY (CODICE_FISCALE, SCADENZA),
    CONSTRAINT FK_DOCUMENTO_PERSONA
        FOREIGN KEY (CODICE_FISCALE) REFERENCES PERSONA(CODICE_FISCALE),
    CONSTRAINT FK_DOCUMENTO_ENTE
        FOREIGN KEY (PARTITA_IVA) REFERENCES ENTE(PARTITA_IVA)
);


CREATE TABLE PRENOTAZIONE (
    CODICE_PRENOTAZIONE   NUMBER        NOT NULL,
    DESCRIZIONE           CLOB,
    DATA_PRENOTAZIONE     DATE          NOT NULL,
    DATA_DIMISSIONE       DATE,
    NUMERO_CAMERA         NUMBER,
    CODICE_FISCALE_TUTORE VARCHAR2(16),
    CONSTRAINT PK_PRENOTAZIONE PRIMARY KEY (CODICE_PRENOTAZIONE),
    CONSTRAINT FK_PRENOTAZIONE_TUTORE
        FOREIGN KEY (CODICE_FISCALE_TUTORE) REFERENCES TUTORE(CODICE_FISCALE),
    CONSTRAINT FK_PRENOTAZIONE_CAMERA
        FOREIGN KEY (NUMERO_CAMERA) REFERENCES CAMERA(NUMERO_CAMERA)
);

CREATE TABLE TURNO_PROGRAMMATO (
    CODICE_FISCALE_MEDICO VARCHAR2(16) NOT NULL,
    DATA_INIZIO           DATE         NOT NULL,
    DATA_FINE             DATE         NOT NULL,
    GIORNO                VARCHAR2(16) NOT NULL,
    FASCIA_ORARIA         VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_TURNO_PROGRAMMATO PRIMARY KEY (CODICE_FISCALE_MEDICO, DATA_INIZIO),
    CONSTRAINT FK_TURNO_PROG_MEDICO
        FOREIGN KEY (CODICE_FISCALE_MEDICO) REFERENCES MEDICO(CODICE_FISCALE)
);

CREATE TABLE TURNO_EFFETTUATO (
    FASCIA_ORARIA         VARCHAR2(16) NOT NULL,
    ORA_INIZIO            VARCHAR2(16) NOT NULL,
    ORA_FINE              VARCHAR2(16) NOT NULL,
    GIORNO                DATE         NOT NULL,
    CODICE_FISCALE_MEDICO VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_TURNO_EFFETTUATO
        PRIMARY KEY (FASCIA_ORARIA, GIORNO, CODICE_FISCALE_MEDICO),
    CONSTRAINT FK_TURNOEFF_MEDICO
        FOREIGN KEY (CODICE_FISCALE_MEDICO) REFERENCES MEDICO(CODICE_FISCALE)
);

CREATE TABLE VISITA (
    CODICE_FISCALE_PARENTE   VARCHAR2(16) NOT NULL,
    GIORNO_VISITA            DATE         NOT NULL,
    ORA_INGRESSO             VARCHAR2(16) NOT NULL,
    ORA_USCITA               VARCHAR2(16),
    CODICE_FISCALE_RESIDENTE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_VISITA PRIMARY KEY (CODICE_FISCALE_PARENTE, GIORNO_VISITA),
    CONSTRAINT FK_VISITA_PARENTE
        FOREIGN KEY (CODICE_FISCALE_PARENTE) REFERENCES PARENTE(CODICE_FISCALE),
    CONSTRAINT FK_VISITA_RESIDENTE
        FOREIGN KEY (CODICE_FISCALE_RESIDENTE) REFERENCES RESIDENTE(CODICE_FISCALE)
);
