CREATE OR REPLACE FUNCTION CALCOLA_ETA(CF_PERSONA IN VARCHAR2)
RETURN NUMBER IS
  DATA_NASCITA_PERSONA DATE;
BEGIN
  SELECT DATA_NASCITA INTO DATA_NASCITA_PERSONA
  FROM PERSONA
  WHERE CODICE_FISCALE = CF_PERSONA;
  RETURN TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_NASCITA_PERSONA) / 12);
EXCEPTION
  WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION CONTEGGIO_CAMERE_LIBERE(COD_REPARTO IN VARCHAR2)
RETURN NUMBER IS
  CONTEGGIO_LIBERE NUMBER;
BEGIN
  SELECT COUNT(*) INTO CONTEGGIO_LIBERE
  FROM CAMERA
  WHERE CODICE_REPARTO = COD_REPARTO
    AND NUMERO_CAMERA NOT IN (SELECT NUMERO_CAMERA FROM RESIDENTE);
  RETURN CONTEGGIO_LIBERE;
END;
/

CREATE OR REPLACE FUNCTION CONTEGGIO_FARMACI_ASSEGNATI(CF_PERSONA IN VARCHAR2)
RETURN NUMBER IS
  NUMERO_FARMACI NUMBER;
BEGIN
  SELECT COUNT(*) INTO NUMERO_FARMACI
  FROM ASSUME
  WHERE CODICE_FISCALE = CF_PERSONA;
  RETURN NUMERO_FARMACI;
END;
/

CREATE OR REPLACE FUNCTION CALCOLA_STIPENDIO_MENSILE(CF_PERSONALE IN VARCHAR2)
RETURN NUMBER IS
  PAGA_ORARIA_PERSONALE NUMBER;
  ORE_LAVORO_MENSILI NUMBER := 160;
BEGIN
  SELECT CONTRATTO.PAGA_ORARIA INTO PAGA_ORARIA_PERSONALE
  FROM CONTRATTO
  WHERE CONTRATTO.CODICE_FISCALE_PERSONALE = CF_PERSONALE
    AND ROWNUM = 1
  ORDER BY CONTRATTO.CODICE_CONTRATTO DESC;
  RETURN PAGA_ORARIA_PERSONALE * ORE_LAVORO_MENSILI;
EXCEPTION
  WHEN NO_DATA_FOUND THEN RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION VERIFICA_PAI_ATTIVO(CF_RESIDENTE IN VARCHAR2)
RETURN VARCHAR2 IS
  PAI_TROVATO NUMBER;
BEGIN
  SELECT COUNT(*) INTO PAI_TROVATO
  FROM PAI
  WHERE PAI.CODICE_FISCALE_RESIDENTE = CF_RESIDENTE
    AND PAI.DATA_DIMISSIONE IS NULL;
  IF PAI_TROVATO > 0 THEN RETURN 'ATTIVO';
  ELSE RETURN 'NESSUN PAI';
  END IF;
END;
/

CREATE OR REPLACE FUNCTION CONTEGGIO_VISITE_RESIDENTE(CF_RESIDENTE IN VARCHAR2, DATA_INIZIO IN DATE, DATA_FINE IN DATE)
RETURN NUMBER IS
  NUMERO_VISITE NUMBER;
BEGIN
  SELECT COUNT(*) INTO NUMERO_VISITE
  FROM VISITA
  WHERE VISITA.CODICE_FISCALE_RESIDENTE = CF_RESIDENTE
    AND VISITA.GIORNO_VISITA BETWEEN DATA_INIZIO AND DATA_FINE;
  RETURN NUMERO_VISITE;
END;
/

CREATE OR REPLACE FUNCTION DESCRIZIONE_ESITO_TRATTAMENTO(COD_TRATTAMENTO IN VARCHAR2)
RETURN VARCHAR2 IS
  STATO_RAGGIUNTO CHAR(1);
  DESCRIZIONE_ESITO VARCHAR2(4000);
BEGIN
  SELECT TRATTAMENTO.RAGGIUNTO, TRATTAMENTO.ESITO
  INTO STATO_RAGGIUNTO, DESCRIZIONE_ESITO
  FROM TRATTAMENTO
  WHERE TRATTAMENTO.CODICE_TRATTAMENTO = COD_TRATTAMENTO;
  IF STATO_RAGGIUNTO = 'S' THEN
    RETURN 'RAGGIUNTO: ' || DESCRIZIONE_ESITO;
  ELSE
    RETURN 'IN CORSO';
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN RETURN 'TRATTAMENTO NON TROVATO';
END;
/
