CREATE OR REPLACE TRIGGER TRG_IMPEDISCI_MODIFICA_CF_PERSONA
BEFORE UPDATE OF CODICE_FISCALE ON PERSONA
FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'Il codice fiscale della persona non e modificabile');
END;
/

CREATE OR REPLACE TRIGGER TRG_IMPEDISCI_MODIFICA_CF_RESIDENTE
BEFORE UPDATE OF CODICE_FISCALE ON RESIDENTE
FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20002, 'Il codice fiscale del residente non e modificabile');
END;
/

CREATE OR REPLACE TRIGGER TRG_CONTROLLO_DISPONIBILITA_CAMERA
BEFORE INSERT ON RESIDENTE
FOR EACH ROW
DECLARE
  POSTI_TOTALI_CAMERA NUMBER;
  POSTI_OCCUPATI_CAMERA NUMBER;
BEGIN
  SELECT LETTI_TOTALI INTO POSTI_TOTALI_CAMERA
  FROM CAMERA
  WHERE NUMERO_CAMERA = :NEW.NUMERO_CAMERA;
  SELECT COUNT(*) INTO POSTI_OCCUPATI_CAMERA
  FROM RESIDENTE
  WHERE NUMERO_CAMERA = :NEW.NUMERO_CAMERA;
  IF POSTI_OCCUPATI_CAMERA >= POSTI_TOTALI_CAMERA THEN
    RAISE_APPLICATION_ERROR(-20003,
      'Camera ' || :NEW.NUMERO_CAMERA || ' al completo: ' || POSTI_TOTALI_CAMERA || ' posti');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AGGIORNA_DATA_REVISIONE_PAI
BEFORE UPDATE ON PAI
FOR EACH ROW
BEGIN
  :NEW.DATA_REVISIONE := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDA_INSERIMENTO_PAI_TRATTAMENTO
BEFORE INSERT ON NECESSITA
FOR EACH ROW
DECLARE
  RESIDENTE_PAI VARCHAR2(16);
BEGIN
  SELECT CODICE_FISCALE_RESIDENTE INTO RESIDENTE_PAI
  FROM PAI
  WHERE CODICE_PAI = :NEW.CODICE_PAI;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20004, 'PAI non trovato per il trattamento');
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDA_ORARI_VISITA
BEFORE INSERT OR UPDATE ON VISITA
FOR EACH ROW
BEGIN
  IF :NEW.ORA_USCITA IS NOT NULL AND :NEW.ORA_USCITA <= :NEW.ORA_INGRESSO THEN
    RAISE_APPLICATION_ERROR(-20005,
      'Ora uscita deve essere successiva a ora ingresso');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VALIDA_ORARI_TURNO
BEFORE INSERT OR UPDATE ON TURNO_PROGRAMMATO
FOR EACH ROW
BEGIN
  IF :NEW.ORA_FINE <= :NEW.ORA_INIZIO THEN
    RAISE_APPLICATION_ERROR(-20006,
      'Ora fine turno deve essere successiva a ora inizio');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DIMISSIONE_AUTOMATICA_RESIDENTE
AFTER UPDATE OF DATA_DIMISSIONE ON PAI
FOR EACH ROW
BEGIN
  IF :NEW.DATA_DIMISSIONE IS NOT NULL THEN
    DELETE FROM RESIDENTE
    WHERE CODICE_FISCALE = :NEW.CODICE_FISCALE_RESIDENTE;
  END IF;
END;
/
