CREATE OR REPLACE VIEW VISTA_RESIDENTI_ATTIVI AS
SELECT 
    PERSONA.CODICE_FISCALE,
    PERSONA.NOME,
    PERSONA.COGNOME,
    PERSONA.DATA_NASCITA,
    RESIDENTE.NUMERO_CAMERA,
    CAMERA.PIANO,
    REPARTO.NOME_REPARTO
FROM 
    PERSONA
JOIN 
    RESIDENTE ON PERSONA.CODICE_FISCALE = RESIDENTE.CODICE_FISCALE_RESIDENTE
JOIN 
    CAMERA ON RESIDENTE.NUMERO_CAMERA = CAMERA.NUMERO_CAMERA
JOIN 
    REPARTO ON CAMERA.CODICE_REPARTO = REPARTO.CODICE_REPARTO;

CREATE OR REPLACE VIEW VISTA_MEDICI AS
SELECT 
    PERSONA.CODICE_FISCALE,
    PERSONA.NOME,
    PERSONA.COGNOME,
    CONTRATTO.TIPO_CONTRATTO,
    CONTRATTO.PAGA_ORARIA,
    REPARTO.NOME_REPARTO AS RESPONSABILE_DI_REPARTO
FROM 
    PERSONA
JOIN 
    MEDICO ON PERSONA.CODICE_FISCALE = MEDICO.CODICE_FISCALE
JOIN 
    CONTRATTO ON MEDICO.CODICE_CONTRATTO = CONTRATTO.CODICE_CONTRATTO
LEFT JOIN 
    REPARTO ON MEDICO.CODICE_FISCALE = REPARTO.CODICE_FISCALE_RESPONSABILE;

CREATE OR REPLACE VIEW VISTA_TERAPIE_FARMACI AS
SELECT 
    PERSONA.NOME AS NOME_RESIDENTE,
    PERSONA.COGNOME AS COGNOME_RESIDENTE,
    FARMACO.NOME AS NOME_FARMACO,
    FARMACO.DOSE,
    FARMACO.FASCIA_ORARIA,
    ASSUME.DATA_ASSUNZIONE
FROM 
    ASSUME
JOIN 
    FARMACO ON ASSUME.CODICE_FARMACO = FARMACO.CODICE_FARMACO
JOIN 
    RESIDENTE ON ASSUME.CODICE_FISCALE = RESIDENTE.CODICE_FISCALE_RESIDENTE
JOIN 
    PERSONA ON RESIDENTE.CODICE_FISCALE_RESIDENTE = PERSONA.CODICE_FISCALE;

CREATE OR REPLACE VIEW VISTA_TURNI_MEDICI AS
SELECT 
    TURNO_PROGRAMMATO.GIORNO,
    TURNO_PROGRAMMATO.FASCIA_ORARIA,
    TURNO_PROGRAMMATO.ORA_INIZIO,
    TURNO_PROGRAMMATO.ORA_FINE,
    PERSONA.NOME,
    PERSONA.COGNOME,
    MEDICO.CODICE_FISCALE
FROM 
    TURNO_PROGRAMMATO
JOIN 
    MEDICO ON TURNO_PROGRAMMATO.CODICE_FISCALE_MEDICO = MEDICO.CODICE_FISCALE
JOIN 
    PERSONA ON MEDICO.CODICE_FISCALE = PERSONA.CODICE_FISCALE
ORDER BY 
    TURNO_PROGRAMMATO.GIORNO ASC, TURNO_PROGRAMMATO.ORA_INIZIO ASC;

CREATE OR REPLACE VIEW VISTA_REGISTRO_VISITE AS
SELECT 
    VISITA.GIORNO_VISITA,
    VISITA.ORA_INGRESSO,
    VISITA.ORA_USCITA,
    PERSONA_PARENTE.NOME AS NOME_PARENTE,
    PERSONA_PARENTE.COGNOME AS COGNOME_PARENTE,
    PERSONA_RESIDENTE.NOME AS NOME_RESIDENTE,
    PERSONA_RESIDENTE.COGNOME AS COGNOME_RESIDENTE
FROM 
    VISITA
JOIN 
    PARENTE ON VISITA.CODICE_FISCALE_PARENTE = PARENTE.CODICE_FISCALE
JOIN 
    PERSONA PERSONA_PARENTE ON PARENTE.CODICE_FISCALE = PERSONA_PARENTE.CODICE_FISCALE
JOIN 
    RESIDENTE ON VISITA.CODICE_FISCALE_RESIDENTE = RESIDENTE.CODICE_FISCALE_RESIDENTE
JOIN 
    PERSONA PERSONA_RESIDENTE ON RESIDENTE.CODICE_FISCALE_RESIDENTE = PERSONA_RESIDENTE.CODICE_FISCALE
ORDER BY 
    VISITA.GIORNO_VISITA DESC, VISITA.ORA_INGRESSO DESC;

CREATE OR REPLACE VIEW VISTA_PAI_ATTIVI AS
SELECT 
    PAI.CODICE_PAI,
    PERSONA.NOME,
    PERSONA.COGNOME,
    PAI.DATA_REDAZIONE,
    PAI.DATA_REVISIONE,
    PAI.DIAGNOSI
FROM 
    PAI
JOIN 
    RESIDENTE ON PAI.CODICE_FISCALE_RESIDENTE = RESIDENTE.CODICE_FISCALE_RESIDENTE
JOIN 
    PERSONA ON RESIDENTE.CODICE_FISCALE_RESIDENTE = PERSONA.CODICE_FISCALE
WHERE 
    PAI.DATA_DIMISSIONE IS NULL;

CREATE OR REPLACE VIEW VISTA_DISPONIBILITA_LETTI AS
SELECT 
    (SELECT NVL(SUM(LETTI_TOTALI), 0) FROM CAMERA) AS POSTI_TOTALI_STRUTTURA,
    (SELECT COUNT(*) FROM RESIDENTE) AS POSTI_OCCUPATI,
    (SELECT NVL(SUM(LETTI_TOTALI), 0) FROM CAMERA) - (SELECT COUNT(*) FROM RESIDENTE) AS POSTI_LIBERI
FROM DUAL;

CREATE OR REPLACE VIEW VISTA_RECEPTION_RESIDENTI AS
SELECT 
    RESIDENTE.CODICE_FISCALE_RESIDENTE,
    PERSONA.NOME,
    PERSONA.COGNOME,
    RESIDENTE.NUMERO_CAMERA
FROM 
    RESIDENTE
JOIN 
    PERSONA ON RESIDENTE.CODICE_FISCALE_RESIDENTE = PERSONA.CODICE_FISCALE;
